export const departmentData = ref([
  { firstName: 'Phatchanee', lastName: 'Khuhamanee', department: 'Inspection', role: 'Approval' },
  { firstName: 'Treerada', lastName: 'Butrak', department: 'Inspection', role: 'Approval' },
  { firstName: 'Achirawit', lastName: 'Chayanansiri', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Nitchanan', lastName: 'Chaiyapruk', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Phanwadee', lastName: 'Chitchaidi', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Ketsuda', lastName: 'Khantamoon', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Intira', lastName: 'Maiphol', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Julalak', lastName: 'Yodsrithong', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Sumitcha', lastName: 'Suwannachot', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Sarocha', lastName: 'Ngamchawee', department: 'Inspection', role: 'Issuer' },
  { firstName: 'Komkrit', lastName: 'Srisubin', department: 'Office', role: 'Viewer' },
  { firstName: 'TP-1', lastName: 'TP-1', department: 'Production', role: 'Issuer' },
  { firstName: 'TP-2', lastName: 'TP-2', department: 'Production', role: 'Issuer' },
  { firstName: 'Production I', lastName: 'Production I', department: 'Production', role: 'Viewer' },
  { firstName: 'Production II', lastName: 'Production II', department: 'Production', role: 'Viewer' },
  { firstName: 'Suthadta', lastName: 'Kittidanairak', department: 'Sale and marketing', role: 'Issuer' },
  { firstName: 'Kanyakorn', lastName: 'Pawarangkool', department: 'Sale and marketing', role: 'Issuer' },
  { firstName: 'Atikarn', lastName: 'Rungteerabandit', department: 'Sale and marketing', role: 'Issuer' },
  { firstName: 'Sukanya', lastName: 'Unthachai', department: 'Logistic', role: 'Issuer' },
  { firstName: 'Rungthiwa', lastName: 'Sunpakeaw', department: 'Logistic', role: 'Issuer' },
  { firstName: 'Pathamapon', lastName: 'Somjai', department: 'Logistic', role: 'Issuer' },
  { firstName: 'Apinya', lastName: 'Photichanetr', department: 'Warehouse', role: 'Issuer' },
  { firstName: 'Surachai', lastName: 'Prasittinawa', department: 'Warehouse', role: 'Admin' },
  { firstName: 'Therdsak', lastName: 'Seesai', department: 'Warehouse', role: 'Issuer' },
  { firstName: 'Somkiat', lastName: 'Srichala', department: 'Warehouse', role: 'Admin' },
  { firstName: 'Phuwadol', lastName: 'Chonsiri', department: 'Warehouse', role: 'Issuer' },
  { firstName: 'Tunya', lastName: 'Maiket', department: 'Warehouse', role: 'Issuer' },
  { firstName: 'Natthapol', lastName: 'Pattabal', department: 'Warehouse', role: 'Issuer' },
  { firstName: 'Duangjai', lastName: 'Haruthaipoom', department: 'Purchasing', role: 'Viewer' },
  { firstName: 'Praphasri', lastName: 'Namchan', department: 'Purchasing', role: 'Viewer' },
  { firstName: 'Thamonwan', lastName: 'Bamrung', department: 'Purchasing', role: 'Admin' },
  { firstName: 'Poomphan', lastName: 'Phoseewang', department: 'Purchasing', role: 'Approval' },
  { firstName: 'Thanit', lastName: 'Sukthanom', department: 'Purchasing', role: 'Issuer' },
  { firstName: 'Autthawut', lastName: 'Chivapornthip', department: 'SCM', role: 'Admin' },
  { firstName: 'Viewer I', lastName: 'Viewer I', department: 'Viewer', role: 'Viewer' },
  { firstName: 'Viewer II', lastName: 'Viewer II', department: 'Viewer', role: 'Viewer' },
])

export default departmentData
