export const fields = [
  // {
  //   key: 'forwarderId',
  //   label: 'No.',
  //   type: 'text',
  //   required: true,
  //   width: '80px',
  //   searchable: true,
  // },
  {
    key: 'endUserAbb',
    label: 'ABB',
    type: 'text',
    required: true,
    width: '80px',
    searchable: true,
    maxLength: 30,
  },
  {
    key: 'endUserName',
    label: 'End User Name',
    type: 'text',
    required: true,
    width: '250px',
    searchable: true,
  },
  {
    key: 'address',
    label: 'Address',
    type: 'textarea',
    required: true,
    width: '300px',
    searchable: false,
  },
  {
    key: 'contractName',
    label: 'Contact Name',
    type: 'text',
    required: true,
    width: '150px',
    searchable: true,
  },
  {
    key: 'contractNo',
    label: 'Contact No.',
    type: 'text',
    required: true,
    width: '150px',
    searchable: true,
  },
  {
    key: 'taxId',
    label: 'TAX Id',
    type: 'text',
    required: true,
    width: '150px',
    searchable: true,
  },
]
