const dataHeader = ref({
  rmInspectionRequestFormJournalId: null,
  productId: "",
  productName: "",
  supplierId: "",
  supplierName: "",
  tradeName: "",
  makerName: "",
  coAChecked: false,
  remark: "",
  note: "",
  limConditionDetail: "",
  sktLot: "",
  purchaseOrderNo: "",
  purchasingQuantityPcs: 0,
  actualCheck: true,
  inspStaffUpdateBy: "",
  inspStaffUpdateDate: "",
  whUpdateBy: "",
  whUpdateDate: "",
  receivedDate: "",
  isAccept: false,
  isReject: false,
  statusComments: "",
  packagingImg: null,
})
