export const fields = [
  {
    key: 'termOfPaymentId',
    type: 'text',
    hideInTable: true,
    hideInForm: true,
    searchable: false,
  },
  {
    key: 'abb',
    label: 'ABB',
    type: 'text',
    required: true,
    width: '100px',
    searchable: true,
    maxLength: 30,
  },
  {
    key: 'termOfPaymentName',
    label: 'Term Of Payment Name',
    type: 'text',
    required: true,
    width: '250px',
    searchable: true,
  },
  {
    key: 'startDateLabel',
    label: 'Start Date',
    type: 'text',
    width: '150px',
    searchable: false,
    hideInForm: true,
    editKey: 'startDateType',
    editType: 'select',
    editOptions: [
      { label: 'B/L Date', value: 'BL_DATE' },
      { label: 'End Month', value: 'END_MONTH' },
      { label: 'No Due Date', value: 'NO_DUE_DATE' },
    ],
  },
  {
    key: 'startDateType',
    label: 'Start Date',
    type: 'select',
    required: true,
    searchable: false,
    hideInTable: true,
    options: [
      { label: 'B/L Date', value: 'BL_DATE' },
      { label: 'End Month', value: 'END_MONTH' },
      { label: 'No Due Date', value: 'NO_DUE_DATE' },
    ],
  },
  {
    key: 'days',
    label: 'Days',
    type: 'number',
    required: true,
    width: '100px',
    searchable: false,
  },
]
